sonar.projectKey=Molvilada_TutorialCancionesTags
sonar.organization=molvilada

sonar.sources=src
sonar.language=python
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
sonar.exclusions=src/vista/**
