sonar.projectKey=Molvilada_TutorialCancionesTags
sonar.organization=molvilada

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
sonar.coverage.exclusions=**tests/**,**src/vista/**,**docs/**,**setup.py**
