sonar.projectKey=Molvilada_TutorialCancionesTags
sonar.organization=molvilada

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**tests/**,**src/vista/**,**docs/**,**setup.py**
